/lidar_registration_node:
  ros__parameters:
    situation: "lab"
    cost_thres: 2.5
    map_path: "resource/final5.pcd"
    pub_map_grid_size: 0.01
    #RM2025
    al_map_grid_size: 0.27
    #RM2025
    #al_map_grid_size: 0.2
    pc_grid_size: 0.3
    use_saved_T: false
    use_prepoints: false
    is_one_lidar: false

/avia:
  /dynamic_cloud_node:
    ros__parameters:
      is_real: true
      situation: "lab"
      dynamic.sub_topic: "/livox/lidar_3JEDM7A00106241"
      dynamic.pub_topic: "/livox/avia"
      dynamic.frame_id: "lidar_avia_frame"
      dynamic.accumulate: 3
      dynamic.filter_mode: "pcd"
      sor.thres: 0.25
      sor.MeanK: 5
      sor.remove_outlier: true

      pc.map_path: "resource/final5.pcd"
      pc.dis_thres: 0.04
      pc.thread: 12
      mesh.mesh_ori: "resource/24_bg2align_fix1.stl"
      mesh.mesh_filter: "resource/24_bg2filter_fix1.stl"
      mesh.init_translate: [0.0, 0.0, 0.0]
      voxel_grid.voxel_size: 0.06
      voxel_grid.dilate_size: 1
      voxel_grid.size.min: [0.150, 0.150, 0.0]
      voxel_grid.size.max: [27.850, 14.850, 1.500]
      voxel_grid.occupy_expand: 0.11

/mid70:
  /dynamic_cloud_node:
    ros__parameters:
      is_real: true
      situation: "lab"
      dynamic.sub_topic: "/livox/lidar_3GGDL82001UK381"
      dynamic.pub_topic: "/livox/mid70"
      dynamic.frame_id: "lidar_mid70_frame"
      dynamic.accumulate: 4
      dynamic.filter_mode: "pcd"
      sor.thres: 0.25
      sor.MeanK: 5
      sor.remove_outlier: true

      pc.map_path: "resource/final5.pcd"
      pc.dis_thres: 0.04
      pc.thread: 12
      mesh.mesh_ori: "resource/24_bg2align_fix1.stl"
      mesh.mesh_filter: "resource/24_bg2filter_fix1.stl"
      mesh.init_translate: [ 0.0, 0.0, 0.0 ]
      voxel_grid.voxel_size: 0.06
      voxel_grid.dilate_size: 1
      voxel_grid.size.min: [ 0.150, 0.150, 0.0 ]
      voxel_grid.size.max: [ 27.850, 14.850, 1.500 ]
      voxel_grid.occupy_expand: 0.11

/dynamic_cloud_node:
  ros__parameters:
    is_real: true
    situation: "lab"
    dynamic.sub_topic: "/livox/lidar_3JEDM7A00106241"
    dynamic.pub_topic: "/livox/lidar_dynamic"
    dynamic.frame_id: "livox_frame"
    dynamic.accumulate: 3
    dynamic.filter_mode: "pcd"
    sor.thres: 0.6
    #10
    sor.MeanK: 5
    sor.remove_outlier: true

    pc.map_path: "resource/final2.pcd"
    pc.dis_thres: 0.04
    pc.thread: 12

    mesh.mesh_ori: "resource/24_bg2align_fix1.stl"
    mesh.mesh_filter: "resource/24_bg2filter_fix1.stl"
    mesh.init_translate: [0.0, 0.0, 0.0]
    #体素大小
    voxel_grid.voxel_size: 0.06
    voxel_grid.dilate_size: 1
    voxel_grid.size.min: [0.150, 0.150, 0.0]
    voxel_grid.size.max: [27.850, 14.850, 1.500]
    #地图膨胀
    #0.17
    voxel_grid.occupy_expand: 0.11

/cluster_node:
  ros__parameters:
    cluster.min_pts_k: 1600.0
    cluster.min_pts: 3
    #0.3
    cluster.eps: 0.25
    cluster.mode: "nor"

/kalman_filter_node:
  ros__parameters:
    situcation: "rm25"
    is_one_lidar: false
    classWithoutCar: 12

    cluster.eps: 0.25
    cluster.min_pts: 5

    kalman.detect_r: 3.0
    kalman.car_max_speed: 2.0
    kalman.dt_: 0.1
    kalman.sigma_q_x: 40.0
    kalman.sigma_q_y: 40.0
    kalman.sigma_r_x: 10.0
    kalman.sigma_r_y: 10.0

    cost.distance_weight: 1.0
    cost.distance_thres: 6.0
    cost.color_weight: 0.0
    fusion.match_thresh: 0.85

    #----点云聚类和卡尔曼匹配----
    clu.match_thres: 0.85
    #大了导致两个kal与两个clus匹配交换，小了导致kal在拐弯时跟不上clus(跟踪器问题)
    clu.dis_thres: 1.8
    #需要新增卡尔曼的两聚类最小距离阈值
    clu.min_dis_thres: 0.8

    #----相机识别和点云聚类匹配----3d
    cam.match_thres: 0.8
    cam.dis_thres: 1.7
    cam.dis_weight: 0.77
    cam.his_weight: 0.23
    cam.time_offset: 0.0

    #----相机识别和点云聚类匹配----2d
    rect.iou_weight: 0.25
    rect.dis_weight: 0.75
    rect.iou_thres: 0.1
    rect.dis_thres: 2.3
    rect.match_thres: 0.0
    rect.use_rect2d: true
