%YAML:1.0
---
general:
  cam_use_saved_T: true
  classWithoutCar: 10

save:
  save_bag_path: "/media/thesky/THESKY/bags/"
  lidarTopicName: "/livox/lidar_3JEDM7A00106241 /livox/lidar_3GGDL82001UK381"

port:
  speed: 115200
  dataBits: 8
  stopBits: 1
  parity: 'N'

class_mapping:
  B1: 0
  B2: 1
  B3: 2
  B4: 3
  B7: 4
  R1: 5
  R2: 6
  R3: 7
  R4: 8
  R7: 9

  0: B1
  1: B2
  2: B3
  3: B4
  4: B7
  5: R1
  6: R2
  7: R3
  8: R4
  9: R7

net:
  isArmor: false
  trt_path: "resource/model/e1_4.trt"
  onnx_path: "resource/model/e1_4.onnx"
  # 神经网络相关参数
  obj_thres: 0.5        #
  conf_thres: 0.5       #
  nms_thres: 0.3        #
  batch_size: 1         #
  num_class: 1         #
  input_w: 1440       #  输入onnx的宽
  input_h: 1088       #  输入onnx的长

net_60:
  isArmor: false
  trt_path: "resource/model/e1_4.trt"
  onnx_path: "resource/model/e1_4.onnx"       #   onnx文件路径
  # 神经网络相关参数
  obj_thres: 0.25        #
  conf_thres: 0.5       #
  nms_thres: 0.3        #
  batch_size: 1         #
  num_class: 1         #
  input_w: 2464       #  输入onnx的宽
  input_h: 2048       #  输入onnx的长

net_armor:
  isArmor: true
  # 神经网络相关参数
  trt_path: "resource/model/ra0801.trt"         #   engine文件路径
  onnx_path: "resource/model/ra0801.onnx"       #   onnx文件路径
  obj_thres: 0.2        #
  conf_thres: 0.2       #
  nms_thres: 0.45        #
  batch_size: 1         #
  num_class: 10         #
  input_w: 224       #  输入onnx的宽
  input_h: 224       #  输入onnx的长

map:
  mapPath: "resource/map_25_national.jpg"                    # 小地图
  mapImage_winname: "map"
  map_w: 1920
  map_h: 1039

test:
  is_test: true
  rect:
    w: 30
    h: 30

# 00F26632053
Hik30:
  gain: 17
  exposureTime: 10000
  gamma: 0.9
  fps: 80
  camNum: 1
  winname: "Hik30"

  K: !!opencv-matrix # 30
    rows: 3
    cols: 3
    dt: f
    data: [ 1703.57857839016,0.0,776.621431609538,
            0.0,1698.69114037183,558.752840063006,
            0.0, 0.0, 1.0 ]

  point_num: 6

  red:
    pts_pnp_2d:
      #     rm25
      #      - [ 7.06806, 3.35, 0.0 ]
      #      - [ 11.59061, 4.84078, 0.30]
      #      - [ 18.91038, 4.20, 0.80]
      #      - [ 22.50194, 5.20127, 0.0]
      #      - [ 24.97524, 0.0, 0.20]
      #      - [ 13.77016, 0.14, 0.55]
      #     rm25 national
      - [ 7.06806, 3.35, 0.0 ]
      - [ 11.59061, 4.84078, 0.30 ]
      - [ 20.20270, 4.20, 0.80 ]
      - [ 22.82524, 5.19873, 0.0 ]
      - [ 24.97524, 0.0, 0.20 ]
      - [ 13.77016, 0.14, 0.55 ]

  blue:
    pts_pnp_2d:
      #     rm25
      #      - [20.93194, 11.65, 0.0]
      #      - [16.40939, 10.15922, 0.30]
      #      - [9.08962, 10.8, 0.80]
      #      - [5.49806, 9.79873, 0.0]
      #      - [3.02476, 15.0, 0.20]
      #      - [14.22984, 14.86, 0.55]
      #     rm25 national
      - [ 20.93194, 11.65, 0.0 ]
      - [ 16.40939, 10.15922, 0.30 ]
      - [ 7.79730, 10.8, 0.80 ]
      - [ 5.17476, 9.80127, 0.0 ]
      - [ 3.02476, 15.0, 0.20 ]
      - [ 14.22984, 14.86, 0.55 ]

  picture_size:
    input_w: 1440       #  输入onnx的宽
    input_h: 1080       #  输入onnx的长
  source_path:
    singleImg_path: "/home/thesky/RM25_Radar/src/RPS_Radar24/doc/HiKCA.jpg"                                                   #  图片路径
    picture_dir: "/home/thesky/camera/AC83-EF44/record/Born_of_Fire_1/2024-08-02_19_48_20sec/"                      #  图片文件夹路径
    picture_dir_start: 1200                                                                   #  从文件夹中的第n张图片开始 #
    video_path: "/home/thesky/camera/KESU/img_DATA/radar2023/Record_2023-08-05-21-28-07.mp4"  #  视频路径


# DA1521302
Hik60:
  gain: 23.9
  camNum: 1
  exposureTime: 10000
  gamma: 0.6
  fps: 40
  winname: "Hik60"

  K: !!opencv-matrix # 
    rows: 3
    cols: 3
    dt: f
    data: [ 2291.14722575626,0.0,1103.67246,
            0.0,2291.55696902824,1086.45687,
            0.0, 0.0, 1.0 ]

  point_num: 6
  red:
    pts_pnp_2d:
      #      rm25
      #      - [ 9.08962, 10.8000, 0.80 ]
      #      - [ 14.22984, 14.86, 0.55 ]
      #      - [ 24.3000, 15.0000, 0.2]
      #      - [ 24.33395, 11.04948, 0.73188 ]
      #      - [ 14.68471, 8.71834, 0.30 ]
      #      - [ 10.000, 6.7000, 0.30 ]
      #      rm25 national
      - [ 7.79730, 10.8000, 0.80 ]
      - [ 14.22984, 14.86, 0.55 ]
      - [ 24.3000, 15.0000, 0.2 ]
      - [ 24.33395, 11.04948, 0.73188 ]
      - [ 14.68471, 8.71834, 0.30 ]
      - [ 10.000, 6.7000, 0.30 ]

  picture_size:
    input_w: 2448       #  输入onnx的宽
    input_h: 2048       #  输入onnx的长
  source_path:
    singleImg_path: "/opt/MVS/bin/Temp/Data/Image_20250511200502989.bmp"                                                   #  图片路径
    picture_dir: "/home/thesky/camera/AC83-EF44/record/Born_of_Fire_1/2024-08-02_19_48_20main/"                      #  图片文件夹路径
    picture_dir_start: 1200                                                                   #  从文件夹中的第n张图片开始 #
    video_path: "/media/thesky/THESKY/dataset/test1.mp4"  #  视频路径

cost:
  w_rectDistance: 0.35
  rectDistance_thresh: 140  # normal
  w_3dDistance: 0.4
  distance_thresh: 3.0

Mat:
  perspective_K: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 1.3333333333333333, 0., 0., 0., 1.3333333333333333, 0., 0.,
            0., 1. ]
  H: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 2.0505482037408318, 0.40594222613905995,
            -4517.4784359798259, -0.14039992959075431, 2.060491754262594,
            -410.70753888480783, 0.0004623599834200531,
            6.6859043038557193e-05, 1. ]
  H2: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 0.47327623396963897, -0.16828148569472953,
            2144.3895500990134, -0.013599631791623124, 0.97334992122766018,
            343.17033666673888, -0.00022214997843015351,
            1.5434951091185001e-05, 1. ]
