# 串口协议格式, 通信方式为串口，配置为：波特率 115200，8 位数据位，1 位停止位，无硬件流控，无校验位


# fd       类型  int  打开的串口文件句柄
# speed    类型  int  波特率
# dataBits 类型  int  数据位   取值 为 7 或者8
# stopBits 类型  int  停止位   取值为 1 或者2
# parity   类型  int  效验类型 取值为N,E,O,S
# portChar 类型  char* 串口路径
speed: 115200
dataBits: 8
stopBits: 1
parity: 'N'

#port_path:
#  USB0: "/dev/ttyUSB0"    #  串口路径1
#  USB1: "/dev/ttyUSB1"    #  串口路径2

#
#mode14:
#  0:  7
#  1:  1
#  2:  2
#  3:  3
#  4:  4
#  5:  5
#
#  7:  107
#  8:  101
#  9:  102
#  10: 103
#  11: 104
#  12: 105
#
#
#mode12:
#  0: 7
#  1: 1
#  2: 2
#  3: 3
#  4: 4
#  5: 5
#
#  6:  107
#  7:  101
#  8:  102
#  9:  103
#  10: 104
#  11: 105