# cmake_minimum_required(VERSION 3.4.15)

# set(PROJECT_NAME XY_)
# set(CMAKE_BUILD_TYPE "Debug")

# project(${PROJECT_NAME})
# add_executable(${PROJECT_NAME} Mouse.cpp)


# find_package(OpenCV REQUIRED)
# target_include_directories(${PROJECT_NAME} PRIVATE ${OpenCV_INCLUDE_DIRS})
# target_link_libraries(${PROJECT_NAME} PRIVATE ${OpenCV_LIBRARIES})

